export default [
  {
    id: 1,
    name: 'The Suites Metro Apartment Bandung by Putri',
    city: {
      id: 1,
      name: 'Bandung',
      provinceId: 1,
      province: {
        id: 1,
        name: 'Jawa Barat',
      },
    },
    location: 'Soekarno Hatta street No.689 A (kantor King Property di Lobby C (depan alfa expres) Kel. Jatisari, Kec. Buah Batu, Bandung, Jawa Barat, Indonesia., Batununggal, Bandung, Jawa Barat, Indonesia, 40286',
    imageUri: 'https://ik.imagekit.io/tvlk/apr-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/10043057-11cd3538e5768ded5c6e07cf0c491764.png?tr=q-40,c-at_max,w-740,h-500&_src=imagekit',
    rating: 8.5,
    numberOfReview: 621,
    price: 175000,
    facilities: ['AC', 'Restoran', 'Kolam Renang', 'Parkir', 'Wifi'],
  },
  {
    id: 2,
    name: 'The Trans Luxury Hotel',
    city: {
      id: 1,
      name: 'Bandung',
      provinceId: 1,
      province: {
        id: 1,
        name: 'Jawa Barat',
      },
    },
    location: 'Jl. Gatot Subroto No. 289, Buahbatu, Bandung, Jawa Barat, Indonesia, 40273',
    imageUri: 'https://ik.imagekit.io/tvlk/generic-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/10002404-f2ae40544c03ba073c23b46c959e9e31.jpeg?tr=q-40,c-at_max,w-740,h-500&_src=imagekit',
    rating: 9.0,
    numberOfReview: 5804,
    price: 1322500,
    facilities: ['AC', 'Restoran', 'Kolam Renang', 'Parkir', 'Wifi', 'Resepsionis 24 Jam', 'Lift'],
  },
  {
    id: 3,
    name: 'The Papandayan',
    city: {
      id: 1,
      name: 'Bandung',
      provinceId: 1,
      province: {
        id: 1,
        name: 'Jawa Barat',
      },
    },
    location: 'Jalan Jenderat Gatot Subroto No. 83 Malabar, Lengkong, Lengkong, Bandung, Jawa Barat, Indonesia, 40262',
    imageUri: 'https://ik.imagekit.io/tvlk/generic-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/10005852-04b8f8b8369b52c13c7d36e8dcb35417.jpeg?tr=q-40,c-at_max,w-740,h-500&_src=imagekit',
    rating: 8.8,
    numberOfReview: 4285,
    price: 771375,
    facilities: ['AC', 'Restoran', 'Kolam Renang', 'Parkir', 'Wifi', 'Resepsionis 24 Jam', 'Lift'],
  },
  {
    id: 4,
    name: 'Best Western Premier The Hive',
    city: {
      id: 2,
      name: 'Jakarta Timur',
      provinceId: 2,
      province: {
        id: 2,
        name: 'Daerah Khusus Ibukota Jakarta',
      },
    },
    location: 'Jl. DI Panjaitan Kav. 3 - 4, Cawang, Kramat Jati, Jakarta, Indonesia, 13340',
    imageUri: 'https://ik.imagekit.io/tvlk/generic-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/10000317-1024x724-FIT_AND_TRIM-13100ca291f56d00920c38037ddc8f47.png?tr=q-40,c-at_max,w-740,h-500&_src=imagekit',
    rating: 8.4,
    numberOfReview: 9596,
    price: 450000,
    facilities: ['AC', 'Restoran', 'Kolam Renang', 'Parkir', 'Wifi', 'Resepsionis 24 Jam', 'Lift'],
  },
  {
    id: 5,
    name: 'Hotel Indonesia Kempinski Jakarta',
    city: {
      id: 3,
      name: 'Jakarta Pusat',
      provinceId: 2,
      province: {
        id: 2,
        name: 'Daerah Khusus Ibukota Jakarta',
      },
    },
    location: 'Jalan MH Thamrin No. 1, Thamrin, Jakarta Pusat, Jakarta, Indonesia, 10310',
    imageUri: 'https://ik.imagekit.io/tvlk/generic-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/20020708-8ff9e9be39a6504109b631bd6d7e20a8.jpeg?tr=q-40,c-at_max,w-740,h-500&_src=imagekit',
    rating: 8.9,
    numberOfReview: 3625,
    price: 1996500,
    facilities: ['AC', 'Restoran', 'Kolam Renang', 'Parkir', 'Wifi', 'Resepsionis 24 Jam', 'Lift'],
  },
  {
    id: 6,
    name: 'The Ritz-Carlton Jakarta, Mega Kuningan',
    city: {
      id: 4,
      name: 'Jakarta Selatan',
      provinceId: 2,
      province: {
        id: 2,
        name: 'Daerah Khusus Ibukota Jakarta',
      },
    },
    location: 'Jl. DR. Ide Anak Agung Gde Agung Kav.E.1.1 No. 1, Mega Kuningan, Jakarta Selatan, DKI Jakarta, Kuningan, Setiabudi, Jakarta, Indonesia, 12950',
    imageUri: 'https://ik.imagekit.io/tvlk/generic-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/10022569-76dd1103e0433422979302f934b65ef0.jpeg?tr=q-40,c-at_max,w-740,h-500&_src=imagekit',
    rating: 8.8,
    numberOfReview: 2542,
    price: 1815000,
    facilities: ['AC', 'Restoran', 'Kolam Renang', 'Parkir', 'Wifi', 'Resepsionis 24 Jam', 'Lift'],
  },
  {
    id: 7,
    name: 'Wyndham Surabaya',
    city: {
      id: 5,
      name: 'Surabaya',
      provinceId: 3,
      province: {
        id: 3,
        name: 'Jawa Timur',
      },
    },
    location: 'Jalan Basuki Rahmat 67-73 , Genteng, Surabaya, Jawa Timur, Indonesia, 60271',
    imageUri: 'https://ik.imagekit.io/tvlk/generic-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/10041546-1064x710-FIT_AND_TRIM-c2a53b818f713c318cfff76076714071.jpeg?tr=q-40,c-at_max,w-740,h-500&_src=imagekit',
    rating: 8.7,
    numberOfReview: 5155,
    price: 672000,
    facilities: ['AC', 'Restoran', 'Kolam Renang', 'Parkir', 'Wifi', 'Resepsionis 24 Jam'],
  },
  {
    id: 8,
    name: 'Bumi Surabaya City Resort',
    city: {
      id: 5,
      name: 'Surabaya',
      provinceId: 3,
      province: {
        id: 3,
        name: 'Jawa Timur',
      },
    },
    location: 'Jl. Jendral Basuki Rahmat No. 106 - 128 Surabaya, Genteng, Surabaya, Jawa Timur, Indonesia, 60271',
    imageUri: 'https://ik.imagekit.io/tvlk/generic-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/10000090-1024x652-FIT_AND_TRIM-1b16b1ff0b14652fa52c44daa9acd268.jpeg?tr=q-40,c-at_max,w-740,h-500&_src=imagekit',
    rating: 8.8,
    numberOfReview: 5810,
    price: 1032703,
    facilities: ['Restoran', 'Kolam Renang', 'Parkir', 'Wifi', 'Resepsionis 24 Jam', 'Lift'],
  },
  {
    id: 9,
    name: 'Hotel Ciputra World Surabaya managed by Swiss-Belhotel International',
    city: {
      id: 5,
      name: 'Surabaya',
      provinceId: 3,
      province: {
        id: 3,
        name: 'Jawa Timur',
      },
    },
    location: 'Jalan Mayjen Sungkono No. 87 - 89, Sawahan, Surabaya, Jawa Timur, Indonesia, 60224',
    imageUri: 'https://ik.imagekit.io/tvlk/generic-asset/dgXfoyh24ryQLRcGq00cIdKHRmotrWLNlvG-TxlcLxGkiDwaUSggleJNPRgIHCX6/hotel/asset/10001353-1000x667-FIT_AND_TRIM-0f7d6cd0450e6a4740334b045e01fbac.jpeg?tr=q-40,c-at_max,w-740,h-500&_src=imagekit',
    rating: 8.7,
    numberOfReview: 3693,
    price: 780779,
    facilities: ['AC', 'Restoran', 'Kolam Renang', 'Parkir', 'Wifi', 'Resepsionis 24 Jam', 'Lift'],
  },
];
